const skills = [
  {
    jobTitle: "IT Support Technician",
    company: "Digital Gaming Corporation South Africa",
    location: "Cape Town",
    date: "July 2023 – Present",
    contactPerson: {
      name: "Max Naicker",
      phone: "082 848 0809",
    },
    responsibilities: [
      "Technical Support and User assistance",
      "Troubleshooting of Hardware",
      "Troubleshooting of Software",
      "Software installation via Intune",
      "Upgrade of Windows OS",
      "Managing agreed SLA's",
      "Working within MS Azure, Intune and Exchange",
      "Working on all internal build systems",
      "Created software packages for Intune",
      "Documented set up process for MacOS for Intune enrollment",
      "Deploying print drivers via Intune",
      "SharePoint and OneDrive administration",
      "Administration of CrushFTP",
    ],
  },
  {
    jobTitle: "Desktop Support Technician",
    company: "Nkgwete IT Solutions",
    location: "Cape Town",
    date: "May 2020 – June 2023",
    contactPerson: {
      name: "Darryl Marnitz",
      phone: "083 625 6346",
    },
    responsibilities: [
      "Technical Support and User assistance",
      "Troubleshooting of Hardware",
      "Troubleshooting of Software",
      "Software installation via SCCM",
      "Upgrade of Windows OS",
      "Patching of Network Switches",
      "Managing agreed SLA's",
      "CUCM(Cisco Unified Communications Manager) experience",
      "Documenting Processes and User Guides",
    ],
  },
  {
    jobTitle: "Desktop Support Technician",
    company: "T-Systems South Africa",
    location: "Cape Town",
    date: "May 2017 – May 2020",
    contactPerson: {
      name: "Simone Das Neves",
      phone: "082 922 8002",
    },
    responsibilities: [
      "Technical Support and User assistance",
      "Troubleshooting of Hardware",
      "Troubleshooting of Software",
      "Software installation via SCCM",
      "Upgrade of Windows OS",
      "Managing agreed SLA's",
    ],
  },
  {
    jobTitle: "Desktop Support Technician",
    company: "Nedbank Group IT",
    location: "Cape Town",
    date: "Dec 2015 – Feb 2017",
    contactPerson: {
      name: "Simone Das Neves",
      phone: "082 922 8002",
    },
    responsibilities: [
      "Technical Support and User assistance",
      "Troubleshooting of Hardware",
      "Troubleshooting of Software",
      "Software installation via SCCM",
      "Upgrade of Windows OS",
      "Managing agreed SLA's",
    ],
  },
  {
    jobTitle: "Desktop Support Technician",
    company: "T-Systems South Africa",
    location: "Cape Town",
    date: "Sep 2012 – Dec 2015",
    contactPerson: {
      name: "Simone Das Neves",
      phone: "082 922 8002",
    },
    responsibilities: [
      "Technical Support and User assistance",
      "Troubleshooting of Hardware",
      "Troubleshooting of Software",
      "Software installation via SCCM",
      "Upgrade of Windows OS",
      "Managing agreed SLA's",
    ],
  },
];

export default skills;
